[RFC] Add Raspberry Pi 5 initial support
This patchseries adds initial support of Raspberry Pi 5.
Since the most peripheral is routed though RP1 south bridge,
only debug UART and SD card are supported.

Boot log:
  NOTICE:  BL31: v2.6(release):v2.6-240-gfc45bc492
  NOTICE:  BL31: Built : 12:55:13, Dec  4 2024


  barebox 2026.08.0-00096-g549bcd6aa802 Tue Sep 1 07:54:36 CEST 2026


  Board: Raspberry Pi 5
  ERROR: regulator-fixed sd-vcc-reg.of: probe permanently deferred
  WARNING: sdhci-bcmstb 1000fff000.mmc@fff000.of: Failed to get 'vmmc' regulator (ignored).
  sdhci-bcmstb 1000fff000.mmc@fff000.of: registered as mci0
  ERROR: regulator-fixed wl-on-reg.of: probe permanently deferred
  malloc space: 0x1fd00000 -> 0x3f70ffff (size 506.1 MiB)
  mci0: detected SD card version 3.0
  mci0: registered disk0
  environment load /boot/barebox.env: No such file or directory
  Maybe you have to create the partition.
  barebox@Raspberry Pi 5 Model B Rev 1.0:/

Signed-off-by: Andrei Lalaev <andrey.lalaev@gmail.com>

---
Changes in v2:
- EDITME: describe what is new in this series revision.
- EDITME: use bulletpoints and terse descriptions.
- Link to v1: https://patch.msgid.link/20260901-add-rpi5-support-v1-0-129784fe06fa@gmail.com



--- b4-submit-tracking ---
# This section is used internally by b4 prep for tracking purposes.
{
  "series": {
    "revision": 2,
    "change-id": "20260901-add-rpi5-support-8bfa43e1c9b7",
    "prefixes": [],
    "presubject": "",
    "history": {
      "v1": [
        "20260901-add-rpi5-support-v1-0-129784fe06fa@gmail.com"
      ]
    }
  }
}