arm: dts: bcm2712-rpi: disable wifi SDIO
WiFi/BT is not needed for booting and the SDIO device doesn't response with
the error:

  ERROR: sdhci-bcmstb 1001100000.mmc@1100000.of: SDHCI_INT_ERROR: 0x000c8001
  ERROR: sdhci-bcmstb 1001100000.mmc@1100000.of: ============ SDHCI REGISTER DUMP ===========
  ERROR: sdhci-bcmstb 1001100000.mmc@1100000.of: Sys addr:  0x00000000 | Version:  0x00001002
  ERROR: sdhci-bcmstb 1001100000.mmc@1100000.of: Blk size:  0x00000000 | Blk cnt:  0x00000000
  ERROR: sdhci-bcmstb 1001100000.mmc@1100000.of: Argument:  0x00000000 | Trn mode: 0x00000000
  ERROR: sdhci-bcmstb 1001100000.mmc@1100000.of: Present:   0x000f0000 | Host ctl: 0x00000000
  ERROR: sdhci-bcmstb 1001100000.mmc@1100000.of: Power:     0x0000000f | Blk gap:  0x00000080
  ERROR: sdhci-bcmstb 1001100000.mmc@1100000.of: Wake-up:   0x00000000 | Clock:    0x0000fa07
  ERROR: sdhci-bcmstb 1001100000.mmc@1100000.of: Timeout:   0x0000000e | Int stat: 0x000c8001
  ERROR: sdhci-bcmstb 1001100000.mmc@1100000.of: Int enab:  0x077f003f | Sig enab: 0x00000000
  ERROR: sdhci-bcmstb 1001100000.mmc@1100000.of: ACmd stat: 0x00000000 | Slot int: 0x00000000
  ERROR: sdhci-bcmstb 1001100000.mmc@1100000.of: Caps:      0x55eec832 | Caps_1:   0x8000a527
  ERROR: sdhci-bcmstb 1001100000.mmc@1100000.of: Cmd:       0x0000371a | Max curr: 0x00080008
  ERROR: sdhci-bcmstb 1001100000.mmc@1100000.of: Resp[0]:   0x00000000 | Resp[1]:  0x00000000
  ERROR: sdhci-bcmstb 1001100000.mmc@1100000.of: Resp[2]:   0x00000000 | Resp[3]:  0x00000000
  ERROR: sdhci-bcmstb 1001100000.mmc@1100000.of: Host ctl2: 0x00000000

Therefore disable it.

Signed-off-by: Andrei Lalaev <andrey.lalaev@gmail.com>